# Generated by Django 3.2.3 on 2021-05-31 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=250, verbose_name='問題集名')),
                ('about', models.TextField(verbose_name='問題集概要')),
            ],
            options={
                'verbose_name': '問題集タイトル',
                'verbose_name_plural': '問題集タイトル',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='問題文')),
                ('correct', models.TextField(verbose_name='正解')),
                ('explanation', models.TextField(verbose_name='解説')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questioncollection', verbose_name='所属問題集名')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
    ]
