# Generated by Django 3.2.3 on 2021-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncollection',
            name='attention',
            field=models.TextField(blank=True, verbose_name='注意事項'),
        ),
    ]
