# Generated by Django 3.2.3 on 2021-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_questioncollection_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncollection',
            name='image',
            field=models.ImageField(default='media', upload_to='media', verbose_name='画像'),
        ),
    ]
