# Generated by Django 3.2.3 on 2021-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_questioncollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncollection',
            name='image',
            field=models.ImageField(blank=True, default='images/question.png', upload_to='images/', verbose_name='画像'),
        ),
    ]
