# Generated by Django 3.2.3 on 2021-06-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_questioncollection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncollection',
            name='image',
            field=models.ImageField(blank=True, default='default_image/question.png', upload_to='images/', verbose_name='画像'),
        ),
    ]
