# Generated by Django 3.2.3 on 2021-06-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_questioncollection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('judge', models.CharField(choices=[('正解', 'good'), ('不正解', 'bad')], max_length=10, verbose_name='正誤')),
                ('answer_time', models.IntegerField(default=10000, verbose_name='解答時間')),
                ('correct_answer', models.TextField(verbose_name='問題正解')),
                ('user_answer', models.TextField(verbose_name='ユーザー解答')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questioncollection', verbose_name='所属問題集名')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='所属問題')),
            ],
            options={
                'verbose_name': '解答データ',
                'verbose_name_plural': '解答データ',
            },
        ),
    ]
