# Generated by Django 3.2.3 on 2021-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncollection',
            name='user',
            field=models.CharField(default='Who', max_length=100, verbose_name='問題集作成ユーザー'),
        ),
    ]
